apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: chourouknasri/k8sprojet_users-api:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: myregistrykey

